version: '3.3'
services:
  server:
    image: node:16-alpine
    container_name: chatapp
    command: sh -c "npm install  && npm run build && npm run start:dev"
    volumes:
      - ./:/src/chatapp
    working_dir: /src/chatapp
    ports:
      - '3000:3000'
    restart: 'always'
    networks:
      - proxy
  redis-chat:
    image: redis:latest
    container_name: chatapp-redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'redis-cli PING'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: 'on-failure'
    networks:
      - proxy
networks:
  proxy:
    driver: bridge
